trigger:
  branches:
    include:
      - main
      - rel/*
  paths:
    include:
      - src/SignService/*
      - scripts/Install-WindowsSdkISO.ps1
      - .editorconfig
      - azure-pipelines.server.yml
      - version.json

pr:
  branches:
    include:
      - main
      - rel/*
  paths:
    include:
      - src/SignService/*
      - scripts/Install-WindowsSdkISO.ps1
      - .editorconfig
      - azure-pipelines.server.yml
      - version.json

pool:
  vmImage: windows-latest

variables: 
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  TreatWarningsAsErrors: true

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.x'
  inputs:
    version: 3.1.x

- task: DotNetCoreCLI@2
  displayName: Copy sdk files locally before build
  inputs:
    command: custom
    projects: src/SignService/SignService.csproj
    custom: msbuild
    arguments: '/p:Configuration=$(BuildConfiguration) /t:PrebuildScript'

- task: DotNetCoreCLI@2
  displayName: Build and Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: src/SignService/SignService.csproj
    arguments: '-c $(BuildConfiguration) --output $(build.artifactstagingdirectory)\website\ -r win10-x64'
    zipAfterPublish: True

- publish: $(Build.ArtifactStagingDirectory)\website
  displayName: Publish SignService Artifact
  artifact: SignService
